---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: location-soa-rest
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: location-soa-rest@sha256:05674996fb9f3908d260674bc72d79ba3927a5db2dcb69cf79db4b6a5467b2b9
        namespace: fuse79
      name: latest
